postgres:
  host: postgres
  port: 5432
  user: chat
  password: chat
  db_name: chat
  ssl_mode: disable

http: 
  cors_url: 
  - http://localhost:5173
  - http://localhost:3000
  host: 0.0.0.0 
  port: 8080
  debug_mode: true

migrations_path: file://migrations

logger_debug: true

last_read_sender:
  addr: redis:6379
  db: 0
  password: redispass
  timeout: 1s

message_sender:
  addr: redis:6379
  db: 0
  password: redispass
  timeout: 1s

subject_exist:
  keycloak_url: http://keycloak:8080
  realm: main
  client_id: user-checker-service
  client_secret: user-checker-secret
  timeout: 2s

message_sender_worker:
  enabled: true
  groups_count: 1
  group_number: 0
  messages_limit: 10
  delay: 1s

verify:
  jwks_endpoint: http://keycloak:8080/realms/main/protocol/openid-connect/certs