verify:
  jwks_endpoint: http://keycloak:8080/realms/main/protocol/openid-connect/certs

http: 
  cors_url:
  - http://localhost:5173
  - http://localhost:3000
  host: 0.0.0.0 
  port: 8080

general_hub:
  redis: 
    addr: redis:6379
    db: 0
    password: redispass
    timeout: 1s
  client:
    message_buffer: 10
    write_timeout: 60s
    read_timeout: 60s
    ping_timeout: 50s

handler:
  read_buffer_size_bytes: 1024
  write_buffer_size_bytes: 1024
  check_origin: false